# Generated by Django 3.1.14 on 2023-10-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200513_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='在庫'),
        ),
    ]
